# Generated by Django 3.0.11 on 2021-01-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201220_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default-img.jpg', upload_to='user_avatars'),
        ),
    ]
