# Generated by Django 3.0.11 on 2021-01-30 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210122_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_avatar',
        ),
    ]
