# Generated by Django 3.0.11 on 2020-11-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersignup',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
