# Generated by Django 3.0.11 on 2020-11-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201122_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersignup',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
