# Generated by Django 3.0.11 on 2020-11-25 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201122_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersignup',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Newsletter Signups'},
        ),
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(editable=False)),
                ('newsletter_signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='blog.NewsletterSignup')),
                ('posts_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_sent', to='blog.Post')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
