# Generated by Django 3.0.11 on 2020-11-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201125_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletters',
        ),
    ]
