# Generated by Django 3.0.11 on 2020-11-26 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_newsletters'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersignup',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='blog.Post'),
        ),
    ]
