# Generated by Django 3.0.11 on 2020-11-26 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_newslettersignup_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersignup',
            name='posts',
        ),
    ]
