# Generated by Django 3.0.11 on 2020-11-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_newslettersignup_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='newsletters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.NewsletterSignup'),
        ),
    ]
