# Generated by Django 3.0.11 on 2020-11-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201128_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersignup',
            name='opted_in',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
