# Generated by Django 3.0.11 on 2020-11-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmarked',
        ),
    ]
