# Generated by Django 3.0.11 on 2020-12-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201130_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
