# Generated by Django 3.0.11 on 2020-12-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201201_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postview',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Post Views'},
        ),
        migrations.RemoveField(
            model_name='postview',
            name='viewed_at',
        ),
        migrations.AddField(
            model_name='newslettersignup',
            name='modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='postview',
            name='date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='postview',
            name='modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='newslettersignup',
            name='date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
