# Generated by Django 3.0.11 on 2021-01-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20201220_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='newsletters',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.NewsletterSignup'),
        ),
    ]
